### ISSUE TITLE
MS Clarity by Microsoft isn't detected while it's deployed massively through Bing Ads' tag

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [whotracksme/whotracks.me#265]
https://clarity.microsoft.com is offered free by Bing Ads as an Hotjar alternative 

Scripts are fired as a child script of https://bat.bing.com/bat.js , enabled by a server side configuration in the Bing Ads interface, per Pixel ID
for example on https://www.printemps.com/fr/fr
you get https://d.clarity.ms/s/0.6.32/clarity.js 
https://c.clarity.ms/c.gif

set-cookie: MUID=0BED59749DD460E904F1483E99D46EFE; domain=.clarity.ms; expires=Fri, 10-Mar-2023 11:01:03 GMT; path=/; SameSite=None; Secure; Priority=High;

And explicit cookie sync calls
https://c.bing.com/c.gif?CtsSyncId=1A35234FED704866B6538C156A85A29F&RedC=c.clarity.ms&MXFR=0BED59749DD460E904F1483E99D46EFE 
https://c.clarity.ms/c.gif?CtsSyncId=1A35234FED704866B6538C156A85A29F&MUID=25ECFDFFE4CD6D0C105FECB5E5AE6CD3

data collection occurs in POST requests on https://d.clarity.ms/collect 

While publicly launched in June 2021
https://clarity.microsoft.com/blog/clarity-click-maps-what-can-they-do-for-you/
this tracker is not present in the https://www.whotracks.me/ database !?

**Comment by googleanalyticsresoneo** [comment]
Some resources
Clarity tracking code
https://github.com/microsoft/clarity
Data collection spec
https://docs.microsoft.com/en-us/clarity/clarity-data

**Comment by philipp-classen** [comment]
Thank you for reporting!

At a first glance, I'm not sure why it is not showing up, but I would also have expected it to be detected. Will need to dig deeper to understand what is going on.

**Comment by philipp-classen** [comment]
Looking a sample of raw data, these are candidates for subdomains under which it operates:

```
  31351   "www.clarity.ms"
  19603   "c.clarity.ms"
   6471   "h.clarity.ms"
   6416   "i.clarity.ms"
   6415   "f.clarity.ms"
   6385   "e.clarity.ms"
   6280   "a.clarity.ms"
   6131   "j.clarity.ms"
   6051   "d.clarity.ms"
   4126   "b.clarity.ms"
    758   "g.clarity.ms"
     13   "log.clarity.ms"
```

**Comment by philipp-classen** [comment]
Made some changes now. In March (with the next monthly update), we should see the effects.

**Comment by googleanalyticsresoneo** [comment]
@philipp-classen 
Thanks !
Does it means changes are made in the data processing pipeline or into the tracker signature database ?? (not sure of what is the product architecture as of today)

**Comment by philipp-classen** [comment]
@googleanalyticsresoneo It was an internal change (adding mappings), so unfortunately I cannot link to a diff. In the public data that we release begin of March, I would expected two changes:

* https://s3.amazonaws.com/data.whotracks.me/trackerdb.sql should have additional entries for Microsoft Clarity (currently it doesn't)
* There should be entries in the public computed data sets, which are also used for the WhoTrackMe web site.

**Comment by philipp-classen** [comment]
With the March release of the February data, there MS Clarity is now detected:

https://whotracks.me/trackers/microsoft_clarity.html

![2022_03_02_ms_clarity](https://user-images.githubusercontent.com/1616509/156368397-8e126d64-9acf-4dc6-ac96-2e48c5eb42ac.png)

**Comment by philipp-classen** [comment]
The April release is out, which brought a slight release in reach. Overall the data looks stable, so I'm closing it now.
