### ISSUE TITLE
Tiktok Pixel Analytics / conversion tracking tag is not detected

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [whotracksme/whotracks.me#268]
See for example on https://www.elfcosmetics.com/

Explicit tracking script is loaded by https://analytics.tiktok.com/i18n/pixel/sdk.js?sdkid=BRR4GA0I9JJBU29G8GF0 

Documentation is here 
https://ads.tiktok.com/help/article?aid=9663
https://ads.tiktok.com/help/article?aid=717665906670358459 

About cookies and Titok Pixel https://ads.tiktok.com/help/article?aid=10007540 

[TikTok Pixel Helper plugin](https://chrome.google.com/webstore/detail/tiktok-pixel-helper/aelgobmabdmlfmiblddjfnjodalhidnn)

[About TikTok Pixel Helper](https://ads.tiktok.com/help/article?aid=6713418923846402054)

**Comment by philipp-classen** [comment]
Might relate to https://github.com/whotracksme/whotracks.me/issues/262, which added support for analytics.tiktok.com; the aggregated stats are published here: https://whotracks.me/trackers/tiktok_analytics.html

Would need to investigate further, but on the first glance it is not that tiktok is not detected, but rather that the requests only appear if you grant consent. For instance, if you have Ghostery installed, which provides the data for WhoTracksMe, it will by default block the consent and then the websites do not make requests to tiktok. At least, I could not see any network requests myself in the examples (elfcosmetics.com, or nfl.com). In fact, that would be nice behavior of the websites, as they wait for consent before sharing data.

Just as a clarification: In what setup do you think tiktok tracking is not detected? Can you confirm that you see actual requests in the network monitor? (For instance, if you have enabled an adblocker, it could be that no requests get send out.)

Or is it about whether elfcosmetics.com should be listed in the top sites here: https://whotracks.me/trackers/tiktok_analytics.html Maybe the traffic to the site is not big enough, as it shows only the sites with the most traffic; it is not expected to be a complete list.

**Comment by googleanalyticsresoneo** [comment]
Hi

(after giving consent)

On this site https://www.mondialparebrise.fr/planningmonrdv/view#impact-selection
I see network requests and TikTok is not listed as detected tracker in Ghostery while all trackers are allowed and intelligent tracking is disabled

![2022-04-04 14_20_07-tiktok not detected](https://user-images.githubusercontent.com/282461/161542554-8f7efd24-960a-4b84-a22f-82c93b568ead.png)

![image](https://user-images.githubusercontent.com/282461/161542843-78374903-5627-44f1-ab4b-495cf39a5d20.png)

Same thing on https://www.elfcosmetics.com/

![image](https://user-images.githubusercontent.com/282461/161543082-df6d319a-e792-42c3-bf78-3f5f13e65a8c.png)

Many thanks for your attention

**Comment by philipp-classen** [comment]
Can you please try again? We pushed a update to the patterns recently.

Now I see "TikTok Analytics" being detected on https://www.mondialparebrise.fr/planningmonrdv/view#impact-selection. (To make sure that the site can trigger the request, I disabled all blocking.)

![tiktok](https://user-images.githubusercontent.com/1616509/166701527-80cf3709-5ab1-4212-b58f-56b6cd5a3b8e.png)

**Comment by googleanalyticsresoneo** [comment]
@philipp-classen I confirm, it's working for me too

Many Thanks !
