### ISSUE TITLE
Feature request: detect personal data collection

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [whotracksme/whotracks.me#275]
Since Ad Platforms are getting more and more aggressive in collecting personal data to try reconcile Ad exposure and Ad clicks to people and conversions (and unlawful practices remain widely spread for other actors), it would be very useful if Ghostery could intercept (or just notice) which HTTP requests are sending email addresses and phone number in their GET requests (to start with) 

That would allow to detect personal data leaks in unwanted / unexpected contexts, and highlight practices of trackers / rate how serious they are. 

The purpose is to allow monitoring only a few addresses stored in the Ghostery settings, not a tentative to prevent every PII data leak (which could lead to many false positive or to usability breakages) 

Formats could include
- plain text
- URL encoded value
- MD5 and SH256 signatures 

I couldn't find any extension offering that feature

Thanks for your attention

**Comment by philipp-classen** [comment]
There is a related extension called Local Sheriff, which might be close to the use case that you describe:
https://github.com/ghostery/local-sheriff

It is purely client-side and keeps track of the data that your browser sends (it is not shared with a server). It allows to find examples where personal information is shared with third-parties. It will have false-positives, but you can filter for PII that you are interested in.

For instance, for many services you need to send an email as the login (which is fine). But if that site then calls another site including the same email, Local Sheriff should be able to tell you that the original site leaked your email to a third party.

**Comment by googleanalyticsresoneo** [comment]
@philipp-classen 
[That ](https://github.com/ghostery/local-sheriff) looks like a great extension !
Too bad it has so few users !

I'll give it a try !

One additional feature could be that site owners register to be notified of data leaks happening on their site (like malware notifications through Google Search Console...)

Many Thanks
